import {
  EmirateArea,
  Client,
  Customer,
  Driver,
  Vehicle,
  Order,
  Shipment,
  Payment,
  VehicleLog,
} from '@/types';

export const INITIAL_EMIRATES_AREAS: EmirateArea[] = [
  { id: 'ea-1', emirate: 'Dubai', areaName: 'Business Bay', areaNameAr: 'الخليج التجاري', deliveryCharge: 25, expressCharge: 45, driverCommission: 5, isActive: true },
  { id: 'ea-2', emirate: 'Dubai', areaName: 'Dubai Marina', areaNameAr: 'مرسى دبي', deliveryCharge: 25, expressCharge: 45, driverCommission: 5, isActive: true },
  { id: 'ea-3', emirate: 'Dubai', areaName: 'Downtown Dubai', areaNameAr: 'وسط مدينة دبي', deliveryCharge: 25, expressCharge: 45, driverCommission: 5, isActive: true },
  { id: 'ea-4', emirate: 'Dubai', areaName: 'Deira & Bur Dubai', areaNameAr: 'ديرة وبر دبي', deliveryCharge: 20, expressCharge: 35, driverCommission: 4, isActive: true },
  { id: 'ea-5', emirate: 'Abu Dhabi', areaName: 'Al Reem Island', areaNameAr: 'جزيرة الريم', deliveryCharge: 35, expressCharge: 60, driverCommission: 7, isActive: true },
  { id: 'ea-6', emirate: 'Abu Dhabi', areaName: 'Khalifa City', areaNameAr: 'مدينة خليفة', deliveryCharge: 35, expressCharge: 60, driverCommission: 7, isActive: true },
  { id: 'ea-7', emirate: 'Sharjah', areaName: 'Al Majaz', areaNameAr: 'المجاز', deliveryCharge: 30, expressCharge: 50, driverCommission: 6, isActive: true },
  { id: 'ea-8', emirate: 'Ajman', areaName: 'Al Nuaimia', areaNameAr: 'النعيمية', deliveryCharge: 30, expressCharge: 50, driverCommission: 6, isActive: true },
  { id: 'ea-9', emirate: 'Ras Al Khaimah', areaName: 'Al Nakheel', areaNameAr: 'النخيل', deliveryCharge: 40, expressCharge: 70, driverCommission: 8, isActive: true },
  { id: 'ea-10', emirate: 'Fujairah', areaName: 'Fujairah City', areaNameAr: 'مدينة الفجيرة', deliveryCharge: 45, expressCharge: 75, driverCommission: 10, isActive: true },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    companyName: 'Emirates Global Trading',
    companyNameAr: 'الإمارات للتجارة العالمية',
    contactPerson: 'Tariq Al-Mansoori',
    phone: '+971 50 123 4567',
    email: 'info@egt.ae',
    emirate: 'Dubai',
    address: 'Office 1402, Opal Tower, Business Bay',
    taxNumber: 'TRN-100293847',
    creditLimit: 15000,
    currentBalance: 2450.0,
    isActive: true,
  },
  {
    id: 'cli-2',
    companyName: 'Gulf Luxury Goods LLC',
    companyNameAr: 'الخليج للبضائع الفاخرة',
    contactPerson: 'Sarah Johnson',
    phone: '+971 52 987 6543',
    email: 'sarah@gulfluxury.ae',
    emirate: 'Dubai',
    address: 'Warehouse 12, Al Quoz Industrial 3',
    taxNumber: 'TRN-500998877',
    creditLimit: 25000,
    currentBalance: 5120.0,
    isActive: true,
  },
  {
    id: 'cli-3',
    companyName: 'Arabian Perfumes & Cosmetics',
    companyNameAr: 'العربية للعطور ومستحضرات التجميل',
    contactPerson: 'Rashid Al-Kaitoob',
    phone: '+971 55 333 2211',
    email: 'orders@arabianperfumes.ae',
    emirate: 'Sharjah',
    address: 'Industrial Area 11, Sharjah',
    taxNumber: 'TRN-777123456',
    creditLimit: 10000,
    currentBalance: 850.0,
    isActive: true,
  },
  {
    id: 'cli-4',
    companyName: 'Apex Electronics LLC',
    companyNameAr: 'أبيكس للإلكترونيات',
    contactPerson: 'Michael Chen',
    phone: '+971 54 444 8899',
    email: 'michael@apexelectronics.ae',
    emirate: 'Abu Dhabi',
    address: 'Mussafah Industrial Area M4',
    taxNumber: 'TRN-333444555',
    creditLimit: 30000,
    currentBalance: 0.0,
    isActive: true,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Omar Al-Hassan',
    phone: '+971 50 888 1122',
    emirate: 'Dubai',
    area: 'Business Bay',
    addressLine: 'Executive Towers, Tower B, Apt 1403',
    poBox: '99201',
    latitude: 25.1857,
    longitude: 55.2694,
  },
  {
    id: 'cust-2',
    name: 'Fatima Al-Zahra',
    phone: '+971 52 777 3344',
    emirate: 'Abu Dhabi',
    area: 'Al Reem Island',
    addressLine: 'Gate Towers, Tower 1, Apt 2205',
    poBox: '44012',
    latitude: 24.4952,
    longitude: 54.3982,
  },
  {
    id: 'cust-3',
    name: 'David Smith',
    phone: '+971 55 123 9900',
    emirate: 'Dubai',
    area: 'Dubai Marina',
    addressLine: 'Marina Gate 2, Apt 1804',
    latitude: 25.0805,
    longitude: 55.1403,
  },
  {
    id: 'cust-4',
    name: 'Mariam Al-Nuaimi',
    phone: '+971 56 654 3210',
    emirate: 'Sharjah',
    area: 'Al Majaz',
    addressLine: 'Corniche Plaza, Tower A, Apt 802',
    latitude: 25.3375,
    longitude: 55.3854,
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    plateNumber: '67482',
    plateCode: 'I',
    emirateRegistered: 'Dubai',
    type: 'Van',
    makeModel: 'Toyota HiAce 2024',
    year: 2024,
    status: 'Active',
    odometerKm: 34200,
    insuranceExpiry: '2027-02-15',
    mulkiyaExpiry: '2027-02-15',
  },
  {
    id: 'veh-2',
    plateNumber: '19045',
    plateCode: 'A',
    emirateRegistered: 'Abu Dhabi',
    type: 'Chiller Truck',
    makeModel: 'Isuzu NPR 2023',
    year: 2023,
    status: 'Active',
    odometerKm: 68100,
    insuranceExpiry: '2026-11-30',
    mulkiyaExpiry: '2026-11-30',
  },
  {
    id: 'veh-3',
    plateNumber: '88301',
    plateCode: 'DXB',
    emirateRegistered: 'Dubai',
    type: 'Motorcycle',
    makeModel: 'Yamaha FZ25 2025',
    year: 2025,
    status: 'Active',
    odometerKm: 12400,
    insuranceExpiry: '2027-08-20',
    mulkiyaExpiry: '2027-08-20',
  },
  {
    id: 'veh-4',
    plateNumber: '44109',
    plateCode: '3',
    emirateRegistered: 'Sharjah',
    type: 'Van',
    makeModel: 'Nissan Urvan 2022',
    year: 2022,
    status: 'Maintenance',
    odometerKm: 98500,
    insuranceExpiry: '2026-09-10',
    mulkiyaExpiry: '2026-09-10',
  },
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'drv-1',
    fullName: 'Zayd Al-Farsi',
    phone: '+971 50 444 1122',
    licenseNumber: 'UAE-DL-982103',
    licenseExpiry: '2028-05-20',
    emirate: 'Dubai',
    status: 'On Delivery',
    assignedVehicleId: 'veh-1',
    vehiclePlate: 'Dubai I-67482',
    rating: 4.9,
    completedTodayCount: 14,
  },
  {
    id: 'drv-2',
    fullName: 'Hamdan Al-Shehhi',
    phone: '+971 52 555 3344',
    licenseNumber: 'UAE-DL-443901',
    licenseExpiry: '2027-10-12',
    emirate: 'Abu Dhabi',
    status: 'Active',
    assignedVehicleId: 'veh-2',
    vehiclePlate: 'Abu Dhabi A-19045',
    rating: 4.8,
    completedTodayCount: 9,
  },
  {
    id: 'drv-3',
    fullName: 'Bilal Khan',
    phone: '+971 55 999 0011',
    licenseNumber: 'UAE-DL-776231',
    licenseExpiry: '2026-12-01',
    emirate: 'Dubai',
    status: 'On Delivery',
    assignedVehicleId: 'veh-3',
    vehiclePlate: 'Dubai DXB-88301',
    rating: 4.95,
    completedTodayCount: 18,
  },
  {
    id: 'drv-4',
    fullName: 'Youssef Benali',
    phone: '+971 56 111 2233',
    licenseNumber: 'UAE-DL-110293',
    licenseExpiry: '2027-03-30',
    emirate: 'Sharjah',
    status: 'Off Duty',
    assignedVehicleId: 'veh-4',
    vehiclePlate: 'Sharjah 3-44109',
    rating: 4.7,
    completedTodayCount: 0,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    voucherNo: 'VCH-2026-00101',
    refNo: 'PO-88901',
    billNo: 'INV-4001',
    clientId: 'cli-1',
    clientName: 'Emirates Global Trading',
    customerId: 'cust-1',
    customerName: 'Omar Al-Hassan',
    customerPhone: '+971 50 888 1122',
    emirate: 'Dubai',
    area: 'Business Bay',
    addressLine: 'Executive Towers, Tower B, Apt 1403',
    pickupDriverId: 'drv-1',
    pickupDriverName: 'Zayd Al-Farsi',
    deliveryDriverId: 'drv-1',
    deliveryDriverName: 'Zayd Al-Farsi',
    payType: 'COD',
    orderType: 'Standard',
    chargeFrom: 'Client',
    agentName: 'Ahmed Salem',
    isPickup: true,
    isExchange: false,
    isFragile: false,
    isOnHold: false,
    isCancelled: false,
    quantity: 2,
    productPrice: 350.0,
    deliveryCharge: 25.0,
    taxAmount: 1.25,
    totalAmount: 376.25,
    codAmount: 376.25,
    pickupDate: '2026-08-03',
    deliveryDate: '2026-08-03',
    status: 'Out for Delivery',
    notes: 'Please call recipient 15 mins before arrival.',
    createdAt: '2026-08-03T08:30:00Z',
  },
  {
    id: 'ord-102',
    voucherNo: 'VCH-2026-00102',
    refNo: 'PO-99012',
    billNo: 'INV-4002',
    clientId: 'cli-2',
    clientName: 'Gulf Luxury Goods LLC',
    customerId: 'cust-2',
    customerName: 'Fatima Al-Zahra',
    customerPhone: '+971 52 777 3344',
    emirate: 'Abu Dhabi',
    area: 'Al Reem Island',
    addressLine: 'Gate Towers, Tower 1, Apt 2205',
    pickupDriverId: 'drv-2',
    pickupDriverName: 'Hamdan Al-Shehhi',
    deliveryDriverId: 'drv-2',
    deliveryDriverName: 'Hamdan Al-Shehhi',
    payType: 'CAD',
    orderType: 'Fragile',
    chargeFrom: 'Client',
    agentName: 'Noura Al-Mazrouei',
    isPickup: false,
    isExchange: false,
    isFragile: true,
    isOnHold: false,
    isCancelled: false,
    quantity: 1,
    productPrice: 1200.0,
    deliveryCharge: 35.0,
    taxAmount: 1.75,
    totalAmount: 1236.75,
    codAmount: 0.0,
    pickupDate: '2026-08-03',
    deliveryDate: '2026-08-03',
    status: 'In Transit',
    notes: 'Fragile luxury cosmetics set. Handle with extreme care.',
    createdAt: '2026-08-03T09:15:00Z',
  },
  {
    id: 'ord-103',
    voucherNo: 'VCH-2026-00103',
    refNo: 'PO-77401',
    billNo: 'INV-4003',
    clientId: 'cli-3',
    clientName: 'Arabian Perfumes & Cosmetics',
    customerId: 'cust-3',
    customerName: 'David Smith',
    customerPhone: '+971 55 123 9900',
    emirate: 'Dubai',
    area: 'Dubai Marina',
    addressLine: 'Marina Gate 2, Apt 1804',
    pickupDriverId: 'drv-3',
    pickupDriverName: 'Bilal Khan',
    deliveryDriverId: 'drv-3',
    deliveryDriverName: 'Bilal Khan',
    payType: 'COD',
    orderType: 'Express',
    chargeFrom: 'Customer',
    agentName: 'Ahmed Salem',
    isPickup: true,
    isExchange: false,
    isFragile: true,
    isOnHold: false,
    isCancelled: false,
    quantity: 3,
    productPrice: 480.0,
    deliveryCharge: 45.0,
    taxAmount: 2.25,
    totalAmount: 527.25,
    codAmount: 527.25,
    pickupDate: '2026-08-03',
    deliveryDate: '2026-08-03',
    status: 'Delivered',
    notes: 'Delivered and signed by David Smith at concierge.',
    createdAt: '2026-08-03T07:45:00Z',
  },
  {
    id: 'ord-104',
    voucherNo: 'VCH-2026-00104',
    refNo: 'PO-33201',
    billNo: 'INV-4004',
    clientId: 'cli-1',
    clientName: 'Emirates Global Trading',
    customerId: 'cust-4',
    customerName: 'Mariam Al-Nuaimi',
    customerPhone: '+971 56 654 3210',
    emirate: 'Sharjah',
    area: 'Al Majaz',
    addressLine: 'Corniche Plaza, Tower A, Apt 802',
    payType: 'COD',
    orderType: 'Chiller',
    chargeFrom: 'Client',
    agentName: 'Noura Al-Mazrouei',
    isPickup: false,
    isExchange: true,
    isFragile: false,
    isOnHold: true,
    isCancelled: false,
    quantity: 1,
    productPrice: 250.0,
    deliveryCharge: 30.0,
    taxAmount: 1.5,
    totalAmount: 281.5,
    codAmount: 281.5,
    pickupDate: '2026-08-03',
    deliveryDate: '2026-08-04',
    status: 'On Hold',
    notes: 'Customer requested delivery delay to tomorrow afternoon.',
    createdAt: '2026-08-03T10:00:00Z',
  },
  {
    id: 'ord-105',
    voucherNo: 'VCH-2026-00105',
    refNo: 'PO-11002',
    billNo: 'INV-4005',
    clientId: 'cli-4',
    clientName: 'Apex Electronics LLC',
    customerId: 'cust-1',
    customerName: 'Omar Al-Hassan',
    customerPhone: '+971 50 888 1122',
    emirate: 'Dubai',
    area: 'Downtown Dubai',
    addressLine: 'Burj Residences 4, Apt 901',
    payType: 'CAO',
    orderType: 'Standard',
    chargeFrom: 'Client',
    agentName: 'Ahmed Salem',
    isPickup: false,
    isExchange: false,
    isFragile: true,
    isOnHold: false,
    isCancelled: false,
    quantity: 1,
    productPrice: 1850.0,
    deliveryCharge: 25.0,
    taxAmount: 1.25,
    totalAmount: 1876.25,
    codAmount: 0.0,
    pickupDate: '2026-08-03',
    deliveryDate: '2026-08-03',
    status: 'Pickup Scheduled',
    notes: 'Awaiting driver dispatch from Al Quoz warehouse.',
    createdAt: '2026-08-03T11:20:00Z',
  },
];

export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    id: 'shp-1',
    shipmentCode: 'SHP-DXB-AUH-901',
    originHub: 'Dubai Central Hub (Al Quoz)',
    destinationHub: 'Abu Dhabi Regional Hub (Mussafah)',
    driverId: 'drv-2',
    driverName: 'Hamdan Al-Shehhi',
    vehiclePlate: 'Abu Dhabi A-19045',
    totalOrders: 28,
    status: 'In Transit',
    dispatchedAt: '2026-08-03T07:30:00Z',
    createdAt: '2026-08-03T06:30:00Z',
  },
  {
    id: 'shp-2',
    shipmentCode: 'SHP-DXB-SHJ-402',
    originHub: 'Dubai Central Hub (Al Quoz)',
    destinationHub: 'Sharjah Main Hub',
    driverId: 'drv-4',
    driverName: 'Youssef Benali',
    vehiclePlate: 'Sharjah 3-44109',
    totalOrders: 42,
    status: 'Arrived',
    dispatchedAt: '2026-08-03T05:00:00Z',
    arrivedAt: '2026-08-03T06:15:00Z',
    createdAt: '2026-08-03T04:30:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    receiptNo: 'RCT-2026-8801',
    clientId: 'cli-1',
    clientName: 'Emirates Global Trading',
    amount: 5000.0,
    paymentMode: 'Bank Transfer',
    referenceNo: 'FT-ENBD-992019',
    paymentDate: '2026-08-01',
    notes: 'Monthly settlement for July delivery invoices.',
  },
  {
    id: 'pay-2',
    receiptNo: 'RCT-2026-8802',
    clientId: 'cli-3',
    clientName: 'Arabian Perfumes & Cosmetics',
    amount: 1500.0,
    paymentMode: 'Cheque',
    referenceNo: 'CHQ-ADCB-100293',
    paymentDate: '2026-08-02',
    notes: 'Advance deposit.',
  },
];

export const INITIAL_VEHICLE_LOGS: VehicleLog[] = [
  {
    id: 'log-1',
    vehicleId: 'veh-1',
    plateNumber: 'Dubai I-67482',
    logType: 'Fuel',
    amount: 180.0,
    description: 'Special 95 Super Fuel Refill (75L)',
    logDate: '2026-08-02',
    odometerReading: 34180,
  },
  {
    id: 'log-2',
    vehicleId: 'veh-2',
    plateNumber: 'Abu Dhabi A-19045',
    logType: 'Maintenance',
    amount: 1450.0,
    description: 'Refrigeration unit service & oil filter replacement',
    logDate: '2026-07-28',
    odometerReading: 67800,
  },
  {
    id: 'log-3',
    vehicleId: 'veh-4',
    plateNumber: 'Sharjah 3-44109',
    logType: 'Fine',
    amount: 600.0,
    description: 'Dubai Police Speed Fine (E11 Highway)',
    logDate: '2026-07-25',
  },
];
